"""The ten kart styles."""
from .layout import Style

STYLES = [
    Style("S01", "Classic Sprint", 47.0, 37.0, 42.8, 64.3, frame="ladder3",
          front_bumper="straight", rear_bumper="straight", side_bumper="bar", nose="box", pods="box",
          colour=(0.85, 0.12, 0.10), body_colour=(0.10, 0.10, 0.10),
          blurb="Straight parallel main rails, three-cross ladder, square nose. The reference build."),
    Style("S02", "Arrow", 46.0, 36.5, 42.6, 64.0, frame="taper",
          front_bumper="chevron", rear_bumper="arc", side_bumper="bar_kick", nose="arrow", pods="wedge",
          colour=(0.10, 0.35, 0.80), body_colour=(0.95, 0.95, 0.95),
          blurb="Main rails taper hard into a narrow nose; V-chevron front bumper, arched rear bumper."),
    Style("S03", "Ladder Pro", 47.0, 37.0, 42.8, 64.4, frame="ladder5",
          front_bumper="U", rear_bumper="U", side_bumper="double", nose="box", pods="box",
          colour=(0.15, 0.55, 0.20), body_colour=(0.12, 0.12, 0.12),
          blurb="Five-cross ladder with an extra upper side rail; U-shaped front/rear bumpers, twin-bar side bumpers."),
    Style("S04", "Bowfin", 46.0, 37.5, 42.6, 64.2, frame="bowed",
          front_bumper="arc", rear_bumper="arc", side_bumper="arc", nose="round", pods="round",
          colour=(0.95, 0.55, 0.05), body_colour=(0.10, 0.10, 0.10),
          blurb="Main rails bowed outward around the seat with an X under the floor; curved bumpers all round."),
    Style("S05", "X-Brace", 46.0, 36.0, 42.0, 63.8, frame="xbrace",
          front_bumper="trapezoid", rear_bumper="trapezoid", side_bumper="bar", nose="wedge", pods="wedge",
          colour=(0.45, 0.10, 0.60), body_colour=(0.92, 0.92, 0.92),
          blurb="Full-length X bracing between the main rails for torsional stiffness; trapezoid bumpers."),
    Style("S06", "Perimeter", 47.0, 38.0, 42.8, 64.5, frame="perimeter",
          front_bumper="straight_wide", rear_bumper="straight", side_bumper="hoop", nose="box", pods="full",
          colour=(0.20, 0.20, 0.22), body_colour=(0.95, 0.80, 0.05),
          blurb="Outer perimeter rails carry the side bumpers; wide straight bumpers and full-length side pods."),
    Style("S07", "Spine", 46.5, 37.0, 42.4, 64.0, frame="spine",
          front_bumper="chevron", rear_bumper="straight", side_bumper="bar", nose="f1", pods="slim",
          colour=(0.75, 0.75, 0.78), body_colour=(0.80, 0.05, 0.10),
          blurb="Central backbone tube with diagonal outriggers; F1-style narrow nose cone."),
    Style("S08", "Endurance", 47.0, 37.5, 42.8, 64.4, frame="endurance",
          front_bumper="U", rear_bumper="U", side_bumper="double", nose="round", pods="full",
          colour=(0.05, 0.45, 0.50), body_colour=(0.12, 0.12, 0.12),
          blurb="Heavily triangulated with upper side rails and diagonal floor braces; built for the endurance event."),
    Style("S09", "Featherweight", 46.0, 36.0, 42.0, 63.6, frame="minimal",
          front_bumper="straight", rear_bumper="straight", side_bumper="bar", nose="slim", pods="slim",
          colour=(0.95, 0.85, 0.10), body_colour=(0.10, 0.10, 0.10),
          blurb="Fewest members and shortest overall length - the light-weight option."),
    Style("S10", "Wedge", 46.0, 36.5, 42.8, 64.3, frame="wedge",
          front_bumper="swept", rear_bumper="arc", side_bumper="swept", nose="wedge", pods="wedge",
          colour=(0.85, 0.20, 0.55), body_colour=(0.10, 0.10, 0.10),
          blurb="Plan-view wedge: wide at the engine bay, narrowing to the nose, with swept side bumpers."),
]

BY_CODE = {s.code: s for s in STYLES}
